import { useState } from 'react'
import type { PrototypeController } from '../controllers/usePrototypeController'
import { appreciations, impact, insights } from '../services/prototypeData'
import { Avatar } from './components/Avatar'
import { Icon } from './components/Icon'
import { Logo } from './components/Logo'

export function HeroesPage({ app }: { app: PrototypeController }) {
  const [tab, setTab] = useState<'heroes' | 'helped'>('heroes')
  return <div className="heroes-page">
    <header className="page-heading heroes-heading"><h1>We’re part of each other’s story.</h1><Logo className="heroes-watermark" /></header>
    <section className="impact-banner" aria-label="Your impact"><div className="impact-intro"><span className="round-icon"><Icon name="heart" size={26} /></span><div><h2>Your words matter.</h2><p>Look at the good you’ve put into the world.</p></div></div><div className="impact-stats"><div><strong>{impact.peopleHelped}</strong><span>people you’ve helped</span></div><div><strong>{impact.insightsShared}</strong><span>insights you’ve shared</span></div><div><strong>{app.heroes.length}</strong><span>{app.heroes.length === 1 ? 'Scripture Hero' : 'Scripture Heroes'} for you</span></div></div></section>
    <div className="heroes-tabs"><button className={tab === 'heroes' ? 'active' : ''} aria-pressed={tab === 'heroes'} onClick={() => setTab('heroes')}><Icon name="heart" size={19} /> Your Scripture Heroes <span className="count-pill">{app.heroes.length}</span></button><button className={tab === 'helped' ? 'active' : ''} aria-pressed={tab === 'helped'} onClick={() => setTab('helped')}><Icon name="people" size={19} /> People you’ve helped <span className="count-pill">{impact.peopleHelped}</span></button></div>
    {tab === 'heroes' ? <section aria-label="People whose insights helped you"><div className="section-intro"><h2>A little gratitude goes a long way.</h2><p>These people shared an insight you saved to your helplist. Let them know their words mattered.</p></div><div className="hero-grid">{app.heroes.map(person => {
      const savedPosts = insights.filter(post => post.author.id === person.id && app.saved.some(item => item.postId === post.id))
      return <article className="hero-person-card" key={person.id}><div className="hero-person-top"><Avatar person={person} large /><span className="hero-badge"><Icon name="heart" size={13} /> Your Scripture Hero</span></div><h3>{person.name}</h3><p className="person-location"><Icon name="globe" size={13} /> {person.location}</p><div className="saved-post-summary"><span>AN INSIGHT THAT STAYED WITH YOU</span><p>“{savedPosts[0]?.title}”</p><small><Icon name="bookmark" size={13} /> {savedPosts.length} {savedPosts.length === 1 ? 'insight' : 'insights'} in your helplist</small></div><button className={`button ${app.thanked.includes(person.id) ? 'button-outline' : 'button-soft'}`} onClick={() => app.setDialog({ type: 'message', person, thanks: true })}><Icon name={app.thanked.includes(person.id) ? 'check' : 'mail'} size={17} />{app.thanked.includes(person.id) ? 'Thanked · send another note' : 'Send a little thanks'}</button></article>
    })}</div>{app.heroes.length === 0 && <div className="empty-state"><Icon name="people" size={32} /><h2>Your next connection is waiting.</h2><p>When an insight helps, add it to your helplist. Its author will appear here.</p><a className="button button-primary" href="#home">Explore your feed <Icon name="arrow" /></a></div>}<p className="hero-privacy"><Icon name="lock" size={14} /> Your Soul Questions and saved connections are visible only to you. Thanks are anonymous.</p></section>
    : <section aria-label="Appreciation from the community"><div className="section-intro"><h2>You gave someone a little light.</h2><p>{impact.peopleHelped} people found your insights helpful. These community members chose to share their appreciation and welcome a reply.</p></div><div className="hero-grid">{appreciations.map(item => <article className="hero-person-card appreciation-card" key={item.person.id}><div className="hero-person-top"><Avatar person={item.person} large /><span className="opted-in-label">Open to connecting</span></div><h3>{item.person.name}</h3><p className="person-location"><Icon name="globe" size={13} /> {item.person.location}</p><blockquote>{item.quote}</blockquote><p className="appreciation-source">On your insight<br /><strong>{item.postTitle}</strong></p><button className="button button-outline" onClick={() => app.setDialog({ type: 'message', person: item.person, thanks: false })}><Icon name="message" size={17} /> Send a message</button></article>)}</div><p className="hero-privacy"><Icon name="lock" size={14} /> Helpful confirmations stay anonymous. Names appear here only for members who chose to connect.</p></section>}
    <section className="keep-sharing"><div><Icon name="leaf" size={24} /><div><h2>Someone may need your story today.</h2><p>It doesn’t have to be extraordinary. It just has to be yours.</p></div></div><button className="button button-primary" onClick={() => app.setDialog({ type: 'compose' })}>Share an insight <Icon name="plus" size={18} /></button></section>
  </div>
}
